<?php

namespace Corals\Modules\Slider\database\seeds;

use Illuminate\Database\Seeder;

class SliderOptionsDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('slider_options')->delete();

        \DB::table('slider_options')->insert([
            0 =>
                [
                    'id' => 1,
                    'key' => 'items',
                    'default' => '1',
                    'type' => 'number',
                    'values' => '',
                    'description' => 'The number of items you want to see on the screen.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            1 =>
                [
                    'id' => 2,
                    'key' => 'margin',
                    'default' => '0',
                    'type' => 'number',
                    'values' => '',
                    'description' => 'margin-right(px) on item.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            2 =>
                [
                    'id' => 3,
                    'key' => 'loop',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Infinity loop. Duplicate last and first items to get loop illusion.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            3 =>
                [
                    'id' => 4,
                    'key' => 'center',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Center item. Works well with even an odd number of items.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            4 =>
                [
                    'id' => 5,
                    'key' => 'mouseDrag',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Mouse drag enabled.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            5 =>
                [
                    'id' => 6,
                    'key' => 'touchDrag',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Touch drag enabled.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            6 =>
                [
                    'id' => 7,
                    'key' => 'pullDrag',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Stage pull to edge.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            7 =>
                [
                    'id' => 8,
                    'key' => 'freeDrag',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Item pull to edge.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            8 =>
                [
                    'id' => 9,
                    'key' => 'stagePadding',
                    'default' => '0',
                    'type' => 'number',
                    'values' => '',
                    'description' => 'Padding left and right on stage (can see neighbours).',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            9 =>
                [
                    'id' => 10,
                    'key' => 'merge',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Merge items. Looking for data-merge=\'{number}\' inside item..

',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            10 =>
                [
                    'id' => 11,
                    'key' => 'mergeFit',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Fit merged items if screen is smaller than items value.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            11 =>
                [
                    'id' => 12,
                    'key' => 'autoWidth',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Set non grid content. Try using width style on divs.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            12 =>
                [
                    'id' => 13,
                    'key' => 'startPosition',
                    'default' => '0',
                    'type' => 'number/string',
                    'values' => '',
                    'description' => 'Start position or URL Hash string like \'#id\'.

',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            13 =>
                [
                    'id' => 14,
                    'key' => 'URLhashListener',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Listen to url hash changes. data-hash on items is required.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            14 =>
                [
                    'id' => 15,
                    'key' => 'nav',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Show next/prev buttons.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            15 =>
                [
                    'id' => 16,
                    'key' => 'rewind',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Go backwards when the boundary has reached.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            16 =>
                [
                    'id' => 17,
                    'key' => 'navText',
                    'default' => '[\'next\',\'prev\']',
                    'type' => 'array',
                    'values' => '[["&#x27;next&#x27;","&#x27;prev&#x27;"]]',
                    'description' => 'HTML allowed.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            17 =>
                [
                    'id' => 18,
                    'key' => 'navElement',
                    'default' => 'div',
                    'type' => 'string',
                    'values' => '',
                    'description' => 'DOM element type for a single directional navigation link.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            18 =>
                [
                    'id' => 19,
                    'key' => 'slideBy',
                    'default' => '1',
                    'type' => 'number/string',
                    'values' => '',
                    'description' => 'Navigation slide by x. \'page\' string can be set to slide by page.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            19 =>
                [
                    'id' => 20,
                    'key' => 'dots',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Show dots navigation.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            20 =>
                [
                    'id' => 21,
                    'key' => 'dotsEach',
                    'default' => 'false',
                    'type' => 'number/boolean',
                    'values' => ' ',
                    'description' => 'Show dots each x item.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            21 =>
                [
                    'id' => 22,
                    'key' => 'dotData',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Used by data-dot content.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            22 =>
                [
                    'id' => 23,
                    'key' => 'lazyLoad',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '',
                    'description' => 'Lazy load images. data-src and data-src-retina for highres. Also load images into background inline style if element is not <img>',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            23 =>
                [
                    'id' => 24,
                    'key' => 'lazyContent',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'lazyContent was introduced during beta tests but i removed it from the final release due to bad implementation. It is a nice options so i will work on it in the nearest feature.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            24 =>
                [
                    'id' => 25,
                    'key' => 'autoplay',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Autoplay.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            25 =>
                [
                    'id' => 26,
                    'key' => 'autoplayTimeout',
                    'default' => '5000',
                    'type' => 'number',
                    'values' => '',
                    'description' => 'Autoplay interval timeout.

',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            26 =>
                [
                    'id' => 27,
                    'key' => 'autoplayHoverPause',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Pause on mouse hover.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            27 =>
                [
                    'id' => 28,
                    'key' => 'smartSpeed',
                    'default' => '250',
                    'type' => 'number',
                    'values' => '',
                    'description' => 'Speed Calculate. More info to come..',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            28 =>
                [
                    'id' => 29,
                    'key' => 'autoplaySpeed',
                    'default' => 'false',
                    'type' => 'number/boolean',
                    'values' => '',
                    'description' => 'autoplay speed.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            29 =>
                [
                    'id' => 30,
                    'key' => 'navSpeed',
                    'default' => 'false',
                    'type' => 'number/boolean',
                    'values' => '',
                    'description' => 'Navigation speed.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            30 =>
                [
                    'id' => 31,
                    'key' => 'dotsSpeed',
                    'default' => 'false',
                    'type' => 'number/boolean',
                    'values' => '',
                    'description' => 'Pagination speed.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            31 =>
                [
                    'id' => 32,
                    'key' => 'fluidSpeed',
                    'default' => 'false',
                    'type' => 'number/boolean',
                    'values' => '',
                    'description' => 'Speed Calculate. More info to come..',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            32 =>
                [
                    'id' => 33,
                    'key' => 'dragEndSpeed',
                    'default' => 'false',
                    'type' => 'number/boolean',
                    'values' => '',
                    'description' => 'Drag end speed.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            33 =>
                [
                    'id' => 34,
                    'key' => 'callbacks',
                    'default' => 'true',
                    'type' => 'boolean',
                    'values' => '',
                    'description' => 'Enable callback events.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            34 =>
                [
                    'id' => 35,
                    'key' => 'responsive',
                    'default' => 'false',
                    'type' => 'object',
                    'values' => '',
                    'description' => 'Object containing responsive options. Can be set to false to remove responsive capabilities.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            35 =>
                [
                    'id' => 36,
                    'key' => 'responsiveRefreshRate',
                    'default' => '200',
                    'type' => 'number',
                    'values' => '',
                    'description' => 'Responsive refresh rate.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            36 =>
                [
                    'id' => 37,
                    'key' => 'responsiveBaseElement',
                    'default' => 'window',
                    'type' => 'string',
                    'values' => '',
                    'description' => 'Set on any DOM element. If you care about non responsive browser (like ie8) then use it on main wrapper. This will prevent from crazy resizing.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            37 =>
                [
                    'id' => 38,
                    'key' => 'video',
                    'default' => 'false',
                    'type' => 'boolean',
                    'values' => '[false,true]',
                    'description' => 'Enable fetching YouTube/Vimeo/Vzaar videos.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            38 =>
                [
                    'id' => 39,
                    'key' => 'videoHeight',
                    'default' => 'false',
                    'type' => 'number/boolean',
                    'values' => ' ',
                    'description' => 'Set height for videos.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            39 =>
                [
                    'id' => 40,
                    'key' => 'videoWidth',
                    'default' => 'false',
                    'type' => 'number/boolean',
                    'values' => '',
                    'description' => '',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            40 =>
                [
                    'id' => 41,
                    'key' => 'animateOut',
                    'default' => 'false',
                    'type' => 'array/boolean',
                    'values' => '',
                    'description' => 'Class for CSS3 animation out.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            41 =>
                [
                    'id' => 42,
                    'key' => 'animateIn',
                    'default' => 'false',
                    'type' => 'array/boolean',
                    'values' => '',
                    'description' => 'Class for CSS3 animation in.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 0,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            42 =>
                [
                    'id' => 43,
                    'key' => 'fallbackEasing',
                    'default' => 'swing',
                    'type' => 'string',
                    'values' => '',
                    'description' => 'Easing for CSS2 $.animate.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            43 =>
                [
                    'id' => 44,
                    'key' => 'info',
                    'default' => 'false',
                    'type' => 'function',
                    'values' => '',
                    'description' => 'Callback to retrieve basic information (current item/pages/widths). Info function second parameter is Owl DOM object reference.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            44 =>
                [
                    'id' => 45,
                    'key' => 'nestedItemSelector',
                    'default' => 'false',
                    'type' => 'string/class',
                    'values' => '',
                    'description' => 'Use it if owl items are deep nested inside some generated content. E.g \'youritem\'. Dont use dot before class name.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            45 =>
                [
                    'id' => 46,
                    'key' => 'itemElement',
                    'default' => 'div',
                    'type' => 'string',
                    'values' => '',
                    'description' => 'DOM element type for owl-item.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            46 =>
                [
                    'id' => 47,
                    'key' => 'stageElement',
                    'default' => 'div',
                    'type' => 'string',
                    'values' => '',
                    'description' => 'DOM element type for owl-stage.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            47 =>
                [
                    'id' => 48,
                    'key' => 'navContainer',
                    'default' => 'false',
                    'type' => 'string/class/id/boolean',
                    'values' => '',
                    'description' => 'Set your own container for nav.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
            48 =>
                [
                    'id' => 49,
                    'key' => 'dotsContainer',
                    'default' => 'false',
                    'type' => 'string/class/id/boolean',
                    'values' => '',
                    'description' => 'Set your own container for nav.',
                    'slider_type' => 'OwlCarousel2',
                    'hidden' => 1,
                    'deleted_at' => null,
                    'created_at' => null,
                    'updated_at' => null,
                ],
        ]);
    }
}
